# Config file for Air live reloading
# Docs: https://github.com/air-verse/air

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  follow_symlink = false
  dir = "."
  delay = 1000 # ms
  stop_on_error = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[debug]
  enable = false
  force_polling = false
  polling_interval = 1000

[runner]
  args = []
  env = ["GIN_MODE=debug"]
  forward = false
  output = ""
  error = ""
  allow_stdin = false
  grace_time = 500
  send_interrupt = false
  kill_delay = 500
